-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 20:44:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medical_schedule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medical_schedule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical_schedule` DEFAULT CHARACTER SET utf8 ;
USE `medical_schedule` ;

-- -----------------------------------------------------
-- Table `medical_schedule`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical_schedule`.`Medico` (
  `medi_id` INT NOT NULL AUTO_INCREMENT,
  `medi_email` VARCHAR(400) NOT NULL,
  `medi_senha` VARCHAR(400) NOT NULL,
  `medi_crm` VARCHAR(50) NOT NULL,
  `medi_nome` VARCHAR(400) NOT NULL,
  `medi_telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`medi_id`),
  UNIQUE INDEX `paci_id_UNIQUE` (`medi_id` ASC) VISIBLE,
  UNIQUE INDEX `paci_email_UNIQUE` (`medi_email` ASC) VISIBLE,
  UNIQUE INDEX `paci_cpf_UNIQUE` (`medi_crm` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_schedule`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical_schedule`.`Paciente` (
  `paci_id` INT NOT NULL AUTO_INCREMENT,
  `paci_email` VARCHAR(400) NOT NULL,
  `paci_senha` VARCHAR(400) NOT NULL,
  `paci_cpf` VARCHAR(50) NOT NULL,
  `paci_nome` VARCHAR(400) NOT NULL,
  `paci_telefone` VARCHAR(20) NULL,
  `paci_sexo` VARCHAR(45) NULL,
  `paci_data_nascimento` DATE NULL,
  PRIMARY KEY (`paci_id`),
  UNIQUE INDEX `paci_id_UNIQUE` (`paci_id` ASC) VISIBLE,
  UNIQUE INDEX `paci_email_UNIQUE` (`paci_email` ASC) VISIBLE,
  UNIQUE INDEX `paci_cpf_UNIQUE` (`paci_cpf` ASC) VISIBLE)
ENGINE = InnoDB;

-- one piece é bom
-- piratinha q estica uhul
-- -----------------------------------------------------
-- Table `medical_schedule`.`Consulta` OK
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical_schedule`.`Consulta` (
  `cons_id` INT NOT NULL AUTO_INCREMENT,
  `paci_id` INT NULL,
  `medi_id` INT NULL,
  `cons_data_hora` DATETIME NULL,
  PRIMARY KEY (`cons_id`),
  INDEX `FK_paci_cons_idx` (`paci_id` ASC) VISIBLE,
  INDEX `FK_medi_cons_idx` (`medi_id` ASC) VISIBLE,
  CONSTRAINT `FK_paci_cons`
    FOREIGN KEY (`paci_id`)
    REFERENCES `medical_schedule`.`Paciente` (`paci_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_medi_cons`
    FOREIGN KEY (`medi_id`)
    REFERENCES `medical_schedule`.`Medico` (`medi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
